### PR TITLE
New release

### PR DESCRIPTION
**Pull request by nfantone**
We should merge and publish all these new features, releasing as `0.2.0` to npm.

@disintegrator Could you, please, also:

- Make `develop` the default branch. If you clone the repo, let's assume you want to collaborate and push some code. If you fork, it should also be from that branch.
- Protect `master` branch.
- Create a named tag for the `0.2.0` release before publishing to npm.
- Take a look at the [general Seneca repository guidelines](http://senecajs.org/contribute/details/guidelines.html) and see if you can setup this repository to comply to them.

Thanks!

### CODE REVIEW

**Comment by disintegrator** [comment]
@nfantone set the default branch to develop and set master to protected

**Comment by disintegrator** [comment]
@nfantone skimming through the guidelines, I don't see anything that we are falling short on besides tagging of npm releases

**Comment by nfantone** [comment]
Well... What about labels for issues? If I recall correctly, ours don't
exactly match with the ones proposed by the guide.

**Comment by disintegrator** [comment]
I just checked the issues and they so far we use bug, question and request (I just added it). These are all listed on the guideline page. I have also tagged the closed issues with the most appropriate labels I can pick.

**Comment by nfantone** [comment]
I'd like to have the "discussion" label. #6, for instance, could be labeled as such. What do you think?

**Comment by nfantone** [comment]
> set the default branch to develop and set master to protected

Thank you very much for that.

**Comment by disintegrator** [comment]
Added discussion label

**Comment by nfantone** [comment]
:+1: Great

**Comment by nfantone** [comment]
@disintegrator Many more features added, including multi-pin support, custom queue naming and pre-commit hooks for lint validations.

**Comment by disintegrator** [comment]
Amazing work @nfantone.
As an aside: When I have a sec, I'll move this project to an organisation to make sure you are getting recognised for your contributions.

**Comment by disintegrator** [comment]
If you don't have permission to merge this PR, let me know when you'd like me to do it

**Comment by nfantone** [comment]
@disintegrator I do have permission. But it's your project, really. And, besides, I'd like someone to, at least, do a sanity check on all the crap I'm pushing. 

What I wouldn't be able to do is publish to npm. So, there's that.

Apart from those things, you can merge this PR whenever you want.

**Comment by nfantone** [comment]
>  I'll move this project to an organisation to make sure you are getting recognised for your contributions.

Thanks, man. You don't really need to, though. Seriously.

**Comment by cicavey** [comment]
Any movement here? My team is really excited to use these changes, but would very prefer a public release to npm over a development snapshot. Is there anything I/We can do to help?

**Comment by nfantone** [comment]
@cicavey Merged. @disintegrator will need to push this to npm, though.

**Comment by cicavey** [comment]
Wow. Didn't expect that kind of turnaround. Thanks!

**Comment by nfantone** [comment]
@cicavey Released to `npm` under 0.2.0 tag.

https://www.npmjs.com/package/seneca-amqp-transport

**Pull request merged**
