### PR TITLE
Fixes #11. Support multiple key-value pairs in pins

### LINKED ISSUE #11: Mismatched queue names are used when pin values have more than one key-value pair
The example only uses a single pin, "role:create", which works fine. If you add more detail to the pin such as "role:create,type:random" communication will be impossible. The cause is that the queue names generated to match each pin are not generated correctly by the client resulting in the inability of rabbit to route messages.

I have attempted to fix this (pull request incoming) by extracting the queue name generation to a single common place and then calling in both listen and client code paths. I have also updated the the examples to include multiple value pins.

### PR DESCRIPTION
**Pull request by cicavey**
See #11

### CODE REVIEW

**Comment by nfantone** [comment]
@cicavey I like your approach on this. Could you please:

1) Leave the samples as they were and create new files for the new cases you are displaying. 
2) Try to comply with the linter config.  I'll be adding a pre-commit hook soon to validate this. In the mean time, you can do:

```sh
cd seneca-amqp-transport
node_modules/eslint/bin/eslint.js .
```

You'll see seven errors listed.

**Comment by nfantone** [comment]
@cicavey Actually, I've taken a second look at this and I am inclined to say that this isn't right. It isn't right in current `develop` either, though. In light of [this answer here](https://github.com/disintegrator/seneca-amqp-transport/pull/12#issuecomment-176945650), every `.listen` should generate one and _only one_ queue. If you specify an array of pins, it should create a queue, **but declare multiple bindings to different routng keys**. If you want more than queue, you should declare more than one `.listen`.

**Comment by cicavey** [comment]
Doh! Sorry about the linter. I was rushing after I saw the potential to get a 0.2.0 release out and wanted to get some changes in. 

Great point about the queues. I'm happy to explore this further if you want. I may do it regardless in order to learn.

**Comment by nfantone** [comment]
> Doh! Sorry about the linter. 

Don't be. We are still setting up the repo, so there are no Contribution Guidelines, pre-commit hooks or CI validations to prevent thing like this from happening.

> I'm happy to explore this further if you want. 

Of course. Any help is appreciated.

I'll be reviewing this myself, as well.

**Comment by nfantone** [comment]
@cicavey This will be fixed on the upcoming release.

**Pull request closed without merging**
