### PR TITLE
Plugin overhaul

### PR DESCRIPTION
**Pull request by nfantone**
I was in need of writing JS microservices using RabbitMQ as my messaging system. Seneca seemed like a great fit, but I was _very_ disappointed in seeing that AMQP support is close to nonexistence.

The ["official" plugin](https://github.com/senecajs/seneca-rabbitmq-transport) can't be taken seriously nor be used in a production environment and lacks support. And then, there are [some](https://www.npmjs.com/package/seneca-rabbitmq-transport-improved) [other](https://www.npmjs.com/package/seneca-rabbitmq-transport-v2) [efforts](https://www.npmjs.com/package/seneca-amqp-transport) out there, including this here. All badly documented, tested and formatted. Yours, @disintegrator, was the only one that didn't seem like a complete rip off of the original transport plugin, which was sincerely bad to begin with. Moreover, you have chosen the right name. "seneca-rabbitmq-transport" is just wrong and misleading, since it is not tied to RabbitMQ in particular and can be used with any AMQP broker.

So, instead of forking and creating _yet another AMQP transport plugin_, I decided to make my changes into this PR. Which contains:

+ `pin` attribute support for client and listeners.
+ Multiple queues per `pin` bound to a topic exchange with proper routing keys.
+ Upgraded dependencies, including latest `amqplib`.
+ Better and broader `.gitignore`.
+ Custom semistandard eslint as linter (I've done this since it seems like seneca.js in general has chosen to follow standardjs.com - _and_ I really like my semicolons).
+ `.editorconfig` to match linter config.
+ Updated documentation.
+ Examples that work out of the box.

A few of the things I've modified are somewhat hacky and could be better written. Also, tests are a must and are still lacking. But this could be a step forward towards making this the reference AMQP transport plugin for seneca.js.

### CODE REVIEW

**Comment by richardzyx** [comment]
I had a similar experience, and built node-microservice available on npm. Feel free to check it out!

**Comment by nfantone** [comment]
@richardzyx I'll definitely look into it. Thanks, man.

**Comment by disintegrator** [comment]
I appreciate this contribution greatly @nfantone. For background, my daily work and interests have set me on a path moving away from node.js so I can be slow to respond to issues. Saying that, I'm happy to add you as a contributor if you feel like having a more direct impact on this project. Would you be interested?

In the mean time I'll take a look at this PR and once again thank you so much for the contribution.

**Comment by nfantone** [comment]
@disintegrator I'll be more than happy to contribute! Right now, I feel Seneca is a really good idea that lacks support from some sides. And this is one of them.

If you could take a look at this PR, that would also be fantastic.

**Pull request merged**
